### ISSUE TITLE
REPL is not working

### ISSUE THREAD

**Issue by meownoid** [theam/haskell-do#40] opened 2017-03-17 19:46 UTC
There is just nothing. Also, there is no any useful output in terminal about the problem. Tried on latest version from git.

![screenshot_20170317_224425](https://cloud.githubusercontent.com/assets/20129246/24060217/45ba45ea-0b63-11e7-8beb-a8a71f680f4d.png)

**Comment by meownoid** [comment] 2017-03-17 19:49
There are a lot of errors in developer console though:
```
WebSocket is already in CLOSING or CLOSED state.
{"loaded":true,"filepath":"","console":"main","cells":[{"cellContent":"main = putStrLn \"Hello, world!\"","cellType":"CodeCell","cellId":0}],"author":"","date":"","subtitle":"","title":""}
```
And the first one:
```
WebSocket connection to 'ws://localhost:3000/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```

**Comment by NickSeagull** [comment] 2017-03-17 19:51
Can you try to run `stack build` first in the root of your project and then try to use the console?

Also, try to see if there is a process called `haskelldo-core...` and kill it.

Thanks!

**Comment by meownoid** [comment] 2017-03-17 19:59
1. `stack build` didn't help.
2. There is no a `haskelldo-core` named process.

**Comment by NickSeagull** [comment] 2017-03-18 00:55
I've looked into this, looks like they are the same reasons as #36 .

I can reproduce this

**Comment by NickSeagull** [comment] 2017-06-06 12:48
Irrelevant with new version, closing

**Closed as completed by NickSeagull** 2017-06-06 12:48 UTC
Labels: Bug, High priority
